name: 'Deploy partiel'
permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  deploy-production:
    name: Deploy partiel - production
    runs-on: ubuntu-latest
    environment:
      name: production
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: annuaire-entreprises-data-gouv-fr/github-actions/.github/actions/deploy@v1
        with:
          app-to-deploy: "annuaire-entreprises-site"
          app-repository: "https://github.com/annuaire-entreprises-data-gouv-fr/site.git"
          app-shortname: "website"
          version: "main"
          environment: "production"
          ssh-key: ${{ secrets.SSH_MACHINE_USER_PRIVATE_KEY }}
          ssh-host: ${{ secrets.SSH_PRODUCTION_02 }}
          notify-on-failure: true
          notify-on-success: true
          notify-webhook: ${{ secrets.DEV_EVENT_HOOK }}
