# This workflow will do a clean install of node dependencies, build the source code and run tests

name: 'SEO'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 10,25 * *'

jobs:
  build:
    name: 'Generate SEO files'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
      - name: Install dependencies
        run: npm i
      - name: Run /seo-script/index.ts
        run: npm run script:seo
      - name: Compress seo-files
        run: tar czf ./seo-script/seo-files.tar.gz ./seo-script/dist
      - name: Archive seo-files
        uses: actions/upload-artifact@v3
        with:
          name: seo-files
          path: |
            ./seo-script/seo-files.tar.gz
